### ISSUE TITLE
tuist lint --help is giving the help provided by tuist instead of the lint

### ISSUE THREAD

**Issue by didix21** [tuist/tuist-plugin-lint#19]
## Environment

- Tuist version: 3.16.0
- tuist-plugin-lint: 0.3.0

## Current behavior

After installing `tuist-plugin-lint` and running `tuist lint --help` as the README.md says, it gives the tuist's help instead of the linter one.

```
OVERVIEW: Generate, build and test your Xcode projects.

USAGE: tuist [--help-env] <subcommand>

OPTIONS:
  --help-env              Display subcommands to manage the environment tuist
                          versions.
  -h, --help              Show help information.

SUBCOMMANDS:
  build                   Builds a project
  cache                   A set of utilities related to the caching of targets.
  clean                   Clean all the artifacts stored locally
  dump                    Outputs the manifest as a JSON
  edit                    Generates a temporary project to edit the project in
                          the current directory
  fetch                   Fetches any remote content necessary to interact with
                          the project.
  generate                Generates an Xcode workspace to start working on the
                          project.
  graph                   Generates a graph from the workspace or project in
                          the current directory
  init                    Bootstraps a project
  cloud                   A set of commands to interact with the cloud.
  migration               A set of utilities to assist in the migration of
                          Xcode projects to Tuist.
  plugin                  A set of commands for plugin's management.
  run                     Runs a scheme or target in the project
  scaffold                Generates new project based on a template
  signing                 A set of commands for signing-related operations
  test                    Tests a project
  version                 Outputs the current version of tuist

  See 'tuist help <subcommand>' for detailed help.
```

**Observations:** If I run `tuist lint` the command works as expected.

## Expected behavior

When running `tuist lint --help` the output must be:

```
OVERVIEW: A plugin that extends Tuist with linting code using SwiftLint.

USAGE: plugin-lint <subcommand>

OPTIONS:
  -h, --help              Show help information.

SUBCOMMANDS:
  swiftlint (default)     Lints the code of your projects using SwiftLint.
  version                 Outputs the current version of the plugin.
  version-swiftlint       Outputs the current version of SwiftLint.

  See 'plugin-lint help <subcommand>' for detailed help.
```

**Comment by jeroenleenarts** [comment]
Fun thing is `tuist lint help` does print the expected help information.

**Comment by fortmarek** [comment]
I think that's the behaviour of `ArgumentParser` – if you type in command that `ArgumentParser` doesn't know with `--help`, it immediately shows the high-level `--help`. For example, `tuist command-that-does-not-exist --help` will also show help of tuist.

Since we're executing the plugin commands dynamically, `ArgumentParser` doesn't know about them. I guess technically we could maybe preprocess `--help` as well but that would need additional work.

**Comment by danyf90** [comment]
I see, I'll change the README to suggest tuist lint help then :D

**Comment by danieleformichelli** [comment]
Fixed [here](https://github.com/tuist/tuist-plugin-lint/commit/14fb24792742748e57206ac0d36ce061cb5a0318)

**Comment by didix21** [comment]
@danyf90  I understand tuist, behind the scenes, is using swift-argument-parser, right? If it's the case I think the fix maybe should go to tuist instead of this plugin because right know we can't use the other lint arguments neither. It seems this behavior could be easily changed if we use what they mention on this PR: https://github.com/apple/swift-argument-parser/pull/333

**Comment by didix21** [comment]
It seems the strategy: `uncoditionalRemaining` has been renamed to: https://swiftpackageindex.com/apple/swift-argument-parser/1.2.2/documentation/argumentparser/argumentarrayparsingstrategy/captureforpassthrough

**Comment by danieleformichelli** [comment]
Can you explain better what you mean by

> right know we can't use the other lint arguments neither

?

**Comment by didix21** [comment]
For example: `tuist lint --strict`, tuist is complaining that option `--strict` doesn't exists.

**Comment by fortmarek** [comment]
I don't think that should be related 🤔 But yeah, we should support the extra options if the pluging command supports it for sure.

@didix21 maybe you'd have some time to look into it? The custom parsing logic takes place [here](https://github.com/tuist/tuist/blob/main/Sources/TuistKit/Services/TuistService.swift).
