### ISSUE TITLE
Test project doesn't lint

### ISSUE THREAD

**Issue by vytautas1991** [tuist/tuist-plugin-lint#6]
When I try to run `tuist lint` on test or any other project it throws

`Error: The project's graph can not be found.`

**Comment by danyf90** [comment]
Hey @vytautas1991, could you please provide more info?
- reproducible project
- steps to reproduce the issue

**Comment by vytautas1991** [comment]
- Example project is inside this repository `fixtures/Example1`

- Steps to reproduce the issue: 

1. Clone this repository

2. Execute `tuist fetch` in example projects folder

3. Execute `tuist generate`

4. Execute `tuist lint` or `tuist lint App` and it throws the error

**Comment by laxmorek** [comment]
Hey @danyf90 @vytautas1991 

Im on it with @fortmarek 🤞

**Comment by fortmarek** [comment]
Hey 👋 

The release of [ProjectAutomation](https://github.com/tuist/ProjectAutomation) did not point to `tuist@3.0.1` which included a crucial bugfix for tuist plugins.

You can try out the newest `tuist-lint` version `0.2.1` which should work (tested myself in the fixture).

Feel free to reopen if the issue persists for you.

**Comment by vytautas1991** [comment]
Works great, thanks!
